### ISSUE TITLE
Not able to re-run Submit Queue check

### ISSUE THREAD

**Issue by cyanglaz** [cirruslabs/gh-submit-queue#2]
The `submit queue` ci is great. However, there seems isn't a way to re-run the check.
If a PR is opened while the master is blocked because of a flaky test, we will see a failure in the `submit queue`. After master is green by re-running the flaky test, the `submit queue` does't automatically re-run and there is no way to manually trigger it.

**Comment by cyanglaz** [comment]
the PR is here https://github.com/flutter/plugins/pull/1821. I have already merged the PR tho. I forced it to re-run by a commit.

**Comment by fkorotkov** [comment]
It seems Check Suite events are a bit weird for Check Suites after a re-run. At least it was for the master SHA of flutter/plugins that you are referring to. Worked around in 50f0a0f.

**Comment by fkorotkov** [comment]
@cyanglaz the change was just deployed. Please let me know it it happens again.

**Comment by ditman** [comment]
(/cc @fkorotkov this just happened in the PR above)

**Comment by stuartmorgan-g** [comment]
This is happening a lot in flutter/plugins recently; I feel like I'm hitting it every few days at least. https://github.com/flutter/plugins/pull/4244 is a current example.

Should I file a new issue?
