### ISSUE TITLE
Status is often stale 

### ISSUE THREAD

**Issue by stuartmorgan-g** [cirruslabs/gh-submit-queue#8]
flutter/plugins and is frequently seeing stale status from sumbit-queue, blocking our normal submit process. See also #2 and #3 which makes this particularly problematic.

Currently for instance https://github.com/flutter/plugins/pull/6278 shows red even though the tree is green (and has been for hours) and the detail link goes to
https://github.com/flutter/plugins/runs/7865547809?check_suite_focus=true
which is also green.

**Comment by fkorotkov** [comment]
I think https://github.com/cirruslabs/gh-submit-queue/commit/c30856e79b360632f3151305362dff2e716b004c should help with the stale statuses but also now you can poke the status via `/sq poke`.

**Comment by fkorotkov** [comment]
BTW you'll need to approve a request for new permissions so SQ can get hook about PR comments.

**Comment by stuartmorgan-g** [comment]
@godofredoc Is the permission request above (for flutter/plugins and flutter/packages) something you can approve?

**Comment by fkorotkov** [comment]
There should be an email but I think it can be found around https://github.com/apps/submit-queue page.

**Comment by godofredoc** [comment]
Is there any documentation or context information describing why submit-queue requires access to issues?

**Comment by fkorotkov** [comment]
@godofredoc the permissions request contains the description of why it is needed. 

Context is that submit queue needs read access to issue comments to `/sq poke` comments will be handled.

**Comment by stuartmorgan-g** [comment]
> submit queue needs read access to issue comments to `/sq poke` comments will be handled

Wouldn't those be PR comments, not issue comments?

**Comment by fkorotkov** [comment]
PR is an issue from GitHub perspective. There are separate PR comments which are actually review comments on the diff lines but these are not the one that you'll comment `/sq poke`.
